[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
log4rs = "0.10.0"
lazy_static = "1.4.0"
libds = {path = "/home/lxd/Projects/mini_data_struct/libds" }

